#!/bin/bash
ngx_addon_name=ngx_http_nginx_internals_module
HTTP_MODULES="$HTTP_MODULES ngx_http_nginx_internals_module"
NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_nginx_internals_module.c"
